dhcp:
  listen:
  - 0.0.0.0:67
  maxLeases: 1000
  enableLogging: true
  enableSecurity: false
  subnets:
  - name: default
    network: 192.168.1.0
    prefixLength: 24
    rangeStart: 192.168.1.100
    rangeEnd: 192.168.1.200
    gateway: 192.168.1.1
    dnsServers:
    - 192.168.1.1
    - 8.8.8.8
    domainName: local
    leaseTime: 86400
    maxLeaseTime: 172800
  security: {}
  performance: {}
  logging: {}
  monitoring: {}
